import { Hanken_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import { ReactLenis } from "lenis/react";
import "./globals.css";

const grotesk = Hanken_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-grotesk",
});
const pretorian = localFont({
  src: "../assets/Pretorian.ttf",
  variable: "--font-pretorian",
});
export const metadata = {
  title: "Gestalt Principles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${grotesk.variable} ${pretorian.variable} antialiased`}
    >
      <body>
        <ReactLenis options={{ lerp: 0.05 }} root>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
