import { Bowlby_One } from "next/font/google";
import { ReactLenis, useLenis } from "lenis/react";
import "./globals.css";

const wendy = Bowlby_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-wendy",
});

export const metadata = {
  title: "Gestalt Principles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${wendy.className} antialiased`}>
        <ReactLenis options={{ lerp: 0.05 }} root>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
